
{
    'name': 'Mesa',
    'version': '1.0',
    'summary': 'Restaurant',
    'description': 'Mesa',
    'category': 'My Project',
    'author': 'Enea Cane',
    'website': 'Website',
    'depends': ['base'],
    'data': ['views/employee_view.xml',
             'views/position_view.xml',
             'views/guest_view.xml',
             'views/table_view.xml',
             'views/reservation_view.xml',
             'views/visit_view.xml',
             'views/menu_item_view.xml',
             'views/station_view.xml',
             "views/order_view.xml",
             ],
    'demo': [],
    'installable': True,
    'auto_install': False,
    'application': True,
}
